### PR TITLE
Update for new fan model

### PR DESCRIPTION
**Pull request by bdraco**
Tracks core changes
https://github.com/home-assistant/core/pull/45536

For backcompat, percentage.py is copied from core

### CODE REVIEW

**Comment by bdraco** [comment]
Since I wanted this to work on older HA versions I had to implement `speed`

**Comment by bdraco** [comment]
Tested with a live device.

**Comment by shbatm** [comment]
LGTM, have a few things on the backlog, will roll-up a final HACS version this week.

**Comment by shbatm** [comment]
@bdraco I'm a little disappointed the new HA Fan Model doesn't support the Beaufort Scale for presets like the Bond Bridge does...

image

I think we should be able to say "Alexa, set ceiling fan to Hurricane Force"

**Comment by bdraco** [comment]
> Beaufort Scale

I think google and alexa could use the beaufort scale if we implemented a step size in the fan model.

**Pull request merged**
